# Generated by Django 5.2.7 on 2025-10-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=1024)),
                ('model_path', models.CharField(max_length=1024)),
                ('config', models.JSONField()),
                ('stats', models.JSONField(blank=True, null=True)),
                ('metadata_json', models.CharField(blank=True, max_length=1024, null=True)),
                ('stats_json', models.CharField(blank=True, max_length=1024, null=True)),
                ('fig_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('mask_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('change_log_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('bbox_minx', models.FloatField(blank=True, null=True)),
                ('bbox_miny', models.FloatField(blank=True, null=True)),
                ('bbox_maxx', models.FloatField(blank=True, null=True)),
                ('bbox_maxy', models.FloatField(blank=True, null=True)),
                ('cache_key', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TileSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
