# Generated by Django 5.2.7 on 2025-11-02 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='adjacency',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='class_percentages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='fragmentation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
