# Generated by Django 5.2.7 on 2025-11-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0002_analysis_adjacency_analysis_class_percentages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=256)),
                ('bbox_minx', models.FloatField()),
                ('bbox_miny', models.FloatField()),
                ('bbox_maxx', models.FloatField()),
                ('bbox_maxy', models.FloatField()),
                ('tiles_prefix', models.CharField(blank=True, max_length=256, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
