# Generated by Django 5.2.7 on 2025-11-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0004_wojewodztwo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WojewodztwoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wojewodztwo_id', models.IntegerField(help_text='ID from GeoJSON')),
                ('wojewodztwo_name', models.CharField(help_text='Nazwa from GeoJSON', max_length=100)),
                ('geometry', models.JSONField(help_text='Full GeoJSON geometry (MULTIPOLYGON)')),
                ('bounds', models.JSONField(help_text='Bounding box [minx, miny, maxx, maxy]')),
                ('model_path', models.CharField(max_length=500)),
                ('config', models.JSONField(default=dict, help_text='Analysis parameters')),
                ('zoom', models.IntegerField(default=8)),
                ('original_image_path', models.CharField(help_text='Extracted tiles stitched', max_length=500)),
                ('cropped_image_path', models.CharField(help_text='Cropped to województwo shape', max_length=500)),
                ('mask_path', models.CharField(blank=True, max_length=500, null=True)),
                ('fig_path', models.CharField(blank=True, max_length=500, null=True)),
                ('stats', models.JSONField(default=dict, help_text='Normalized stats')),
                ('stats_json', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata_json', models.CharField(blank=True, max_length=500, null=True)),
                ('change_log_path', models.CharField(blank=True, max_length=500, null=True)),
                ('total_area_km2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['wojewodztwo_name'],
            },
        ),
        migrations.DeleteModel(
            name='Wojewodztwo',
        ),
        migrations.AddIndex(
            model_name='wojewodztwoanalysis',
            index=models.Index(fields=['wojewodztwo_id'], name='Classifier__wojewod_77e041_idx'),
        ),
        migrations.AddIndex(
            model_name='wojewodztwoanalysis',
            index=models.Index(fields=['wojewodztwo_name'], name='Classifier__wojewod_a0116c_idx'),
        ),
    ]
